wget ftp://ftp.ebi.ac.uk/pub/databases/interpro/iprscan/DATA/latest_nopthr
wget ftp://ftp.ebi.ac.uk/pub/databases/interpro/iprscan/DATA/latest_pthr
wget ftp://ftp.sanger.ac.uk/pub/databases/Pfam/current_release/Pfam_ls.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Pfam/current_release/Pfam_fs.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Pfam/current_release/Pfam-A.seed.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/current_release/Pfam/Pfam-B.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Pfam/current_release/Pfam-C.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Rfam/Rfam.full.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Rfam/Rfam.tar.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Rfam/Rfam.seed.gz
wget ftp://ftp.sanger.ac.uk/pub/databases/Rfam/Rfam.desc
